import type { Metadata } from "next";
import TodoList from "./TodoList";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className='flex'>
      <div>
        <TodoList />
      </div>
      <div>{children}</div>
    </main>
  );
}
